crizzo_simpleimprint:
    pattern: /imprint
    defaults: { _controller: crizzo.simpleimprint.controller:base }
crizzo_simpleimprint2:	
    pattern: /imprint.php
    defaults: { _controller: crizzo.simpleimprint.controller:redirect }
